[package]
name = "fractal_tree"
version = "1.0.0"
authors = []

[addresses]
fractal_tree = "0x43f0581028053bb1b1a738c34637203ff015fac6683592ef781722d8e40449e3"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.MoveStdlib]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/move-stdlib"
