[package]
name = "fractal-testnet"
version = "1.0.0"
authors = []

[addresses]
fractal_tree = "0x0b7e4b0868b4d7e190fce77a3259694b2168386f6dbdfa0b496270dce4696779"
aptos_token_objects = "0x4"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/move-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-token-objects"
