[package]
name = "fractal_tree"
version = "1.0.0"
authors = []

[addresses]
fractal_tree = "0x4e2e65c099323ccc865047636f9b418554ef9e5443db68571910b3f9567cb3c0"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.MoveStdlib]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/move-stdlib"
