[package]
name = "fractal_tree"
version = "1.0.0"
authors = []

[addresses]
fractal_tree = "0xd074036289078d10cd2e4042d3013e6c5c5c8edad74896ecb4f317d6a5d56789"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.MoveStdlib]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/move-stdlib"
